#AWS_ACCESS_KEY_ID: "AKIAIEB7IINLBA3C77LA"
#AWS_SECRET_ACCESS_KEY: "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"
#AWS_BUCKET: "testbucket093"

access_key_id: AKIAIEB7IINLBA3C77LA
secret_access_key: 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